### ISSUE TITLE
Add /autocomplete and /get endpoints?

### ISSUE THREAD

**Issue by bluec** [Laralabs/get-address-io#8]
Thanks for the package, we're using it in a little side-project.

Are you able to add the /autocomplete and /get endpoints? They are both documented under the Autocomplete section https://documentation.getaddress.io/

Currently I am instead using the call() method as below but it's not ideal...

```php
get_address()->call('GET', sprintf('autocomplete/%s', $value));
get_address()->call('GET', sprintf('get/%s', $id));
```

I forked and started to try adding the endpoints myself but just got in a terribly confused mess!

**Comment by clnt** [comment]
Hey, no problem cheers :)

Yeah sure I can take a look at this soon and probably get a new release out next week.

**Comment by clnt** [comment]
Hey @bluec 

Apologies for the delay on this one when I have given a rough estimate, it's been a very busy past month, however things are now starting to settle a little so i'll look at getting this done asap. It's definitely not dropped off my radar :)

I'd also like to get some unit testing into this package, however depending on time I'll most likely get the endpoints you want released first before I write tests for everything.

**Comment by bluec** [comment]
Great, thanks for the update Matt.

**Comment by clnt** [comment]
Hey @bluec 

I have got a PR open for the two endpoints you have requested #9, currently I have not tested them as I need to get another key sorted so I have not tagged a release however the changes can be pulled down using `dev-1.0.3-dev` in composer.json if you want to try it out.

I'll look at getting a key sorted over this week to test it and I plan to refactor the package to include some of the other features now available on the API such as distance.

**Comment by bluec** [comment]
Thanks @clnt this is really cool. I will take a look! Sorry for the delay responding... other things have got in the way of my project that uses this.

**Comment by msalmanshahid** [comment]
> Hey @bluec
> 
> I have got a PR open for the two endpoints you have requested #9, currently I have not tested them as I need to get another key sorted so I have not tagged a release however the changes can be pulled down using `dev-1.0.3-dev` in composer.json if you want to try it out.
> 
> I'll look at getting a key sorted over this week to test it and I plan to refactor the package to include some of the other features now available on the API such as distance.

Hey @clnt  Any plans on this? Would be great if you provide this. 
Thanks a lot.

**Comment by clnt** [comment]
Hey @msalmanshahid 

Thanks for the poke on this, I have actually been paying for an API key since last commenting on this issue oops :D 

Last year was quite a busy one for me and I definitely got sidetracked from this! I have added this package onto my list of TODO items to achieve over the next couple of months with the aim of getting the refactor done and all the services provided by getAddress.io available to be utilised by it.

I am going to look at doing the refactor first and re-create the same functionality that is currently supported, but also with the autocomplete/get endpoints that I had partially started. I don't want to commit to any timings but hopefully I can get this initial part of work done this month and a release out.

Once that release is all sorted it will then be a case of adding support in for the remaining services provided by getAddress.io

**Comment by msalmanshahid** [comment]
Thank you @clnt appreciate your response.

So alternatively i am using 
`get_address()->call('GET', sprintf('autocomplete/%s', $value));` which is working nicely at the moment. But if i change it to method POST and send 3rd argument parameters `= ['all'=>true]`  it still returns me 6 addresses, whereas when i try to hit directly via postman it gives me all the addresses under the search.

Any idea why the http used in call() method isn't working properly ?

**Comment by clnt** [comment]
@msalmanshahid  I am not quite sure on the exact answer to that one.

As an update I am actively working on v2.0.0 locally which is coming along nicely. The refactor is mostly done and support for find/autocomplete/get is finished, just some more test coverage and slight changes around the `ExpandedAddress` before I release it.

**Comment by msalmanshahid** [comment]
> As an update I am actively working on v2.0.0 locally which is coming along nicely. The refactor is mostly done and support for find/autocomplete/get is finished, just some more test coverage and slight changes around the `ExpandedAddress` before I release it.

I appreciate your efforts, would be great if you announce release date of `v2.0.0`. thanks alot

**Comment by clnt** [comment]
Version 2.0.0 has now been tagged :) I am going to close this issue now, please open a new one if you have any problems. I'll get other endpoints added when I get more time
